# -*- coding: utf-8 -*-
"""Financial Risk for Loan Approval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SsVF3mtpwuzle-2kkvvFUQq41IuVgLdf

# Financial Risk for Loan Approval
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Loan.csv')
print(df.head())

X = df.drop('LoanApproved', axis=1)
y = df['LoanApproved']

# If the variable only has 1 unique value, remove it from X

cols_to_remove = [col for col in X.columns if X[col].nunique() == 1]
X = X.drop(columns=cols_to_remove)
print("removed columns",cols_to_remove)
print(X.shape)

# Check is there any missing values

print(X.isnull().sum())

"""### There are no any null values in the dataset ###"""

# Check the skewness of each variables in dataset
for col in X.columns:
    if pd.api.types.is_numeric_dtype(X[col]):
        skew_value = X[col].skew()
        print(f"Skewness of {col}: {skew_value}")

# Plot distribution for each numeric variable

for col in X.columns:
    if pd.api.types.is_numeric_dtype(X[col]):
        plt.figure(figsize=(8, 6))
        sns.histplot(X[col], kde=True)
        plt.title(f'Distribution of {col}')
        plt.xlabel(col)
        plt.ylabel('Frequency')
        plt.show()

# check variables have skewness more than 1 and then ckeck are they only have 0,1 values. if not, use logarithamic transformation for that variables
for col in X.columns:
    if pd.api.types.is_numeric_dtype(X[col]):
        skew_value = X[col].skew()
        print(f"Skewness of {col}: {skew_value}")
        if abs(skew_value) > 1:
            unique_values = X[col].unique()
            if set(unique_values) != {0,1}:
                print(f"Applying log transformation to {col}")
                # Add 1 to handle potential zero values before log transformation
                X[col] = np.log1p(X[col])
                print(f"Skewness after transformation of {col}: {X[col].skew()}")
            else:
                print(f"Variable {col} only contains 0 and 1. No transformation applied.")

# Check variables that have skewness more than 1

for col in X.columns:
    if pd.api.types.is_numeric_dtype(X[col]):
        skew_value = X[col].skew()
        if abs(skew_value) > 1:
            print(f"The variable {col} has skewness more than 1: {skew_value}")

# Plot variables that have more than 1 skewness

import matplotlib.pyplot as plt
import seaborn as sns

for col in X.columns:
    if pd.api.types.is_numeric_dtype(X[col]):
        skew_value = X[col].skew()
        if abs(skew_value) > 1:
            plt.figure(figsize=(8, 6))
            sns.histplot(X[col], kde=True)
            plt.title(f'Distribution of {col} (Skewness: {skew_value:.2f})')
            plt.xlabel(col)
            plt.ylabel('Frequency')
            plt.show()

# Apply square root transformation to 'totalDebtToIncomeRatio'
X['TotalDebtToIncomeRatio'] = np.sqrt(X['TotalDebtToIncomeRatio'])

# Print skewness after transformation
print(f"Skewness of totalDebtToIncomeRatio after square root transformation: {X['TotalDebtToIncomeRatio'].skew()}")

# find outliers
def find_outliers_iqr(X):
    outliers = {}
    for col in X.select_dtypes(include=['number']):


        Q1 = X[col].quantile(0.25)
        Q3 = X[col].quantile(0.75)
        IQR = Q3 - Q1

        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        outliers_col = X[(X[col] < lower_bound) | (X[col] > upper_bound)]
        if not outliers_col.empty:
            outliers[col] = outliers_col.shape[0]

    return outliers

outliers_iqr = find_outliers_iqr(X)
print("\nColumns with outliers (using percentile method):")
for col, count in outliers_iqr.items():
    print(f"- {col}: {count} outliers")

X.shape

def cap_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df[column] = df[column].apply(lambda x: lower_bound if x < lower_bound else upper_bound if x > upper_bound else x)
    return df

# Example usage for all numeric columns:
for col in X.select_dtypes(include=['number']).columns:
    X = cap_outliers_iqr(X, col)

X.shape

print(X['BankruptcyHistory'])

X.head()

for col in X.columns:
    print(f"Data type of {col}: {X[col].dtype}")

# since applicationDate not important remove ApplicationDate column from X
X = X.drop('ApplicationDate', axis=1)

X.head()

X = pd.get_dummies(X, drop_first=True) # One-hot encode categorical features
print(X.head())

# Use standard scaling to numerical variables

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
numerical_cols = X.select_dtypes(include=['number']).columns
scaler.fit(X[numerical_cols])
X[numerical_cols] = scaler.transform(X[numerical_cols])

# Iterate through boolean columns and convert them to 0 and 1
for col in X.columns:
    if pd.api.types.is_bool_dtype(X[col]):
        X[col] = X[col].astype(int)

X.head()

# Calculate the correlation matrix
correlation_matrix = X.corr()

# Plot the correlation matrix using a heatmap
plt.figure(figsize=(20, 10))  # Adjust figure size as needed
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Features')
plt.show()

mask=np.triu(np.ones_like(correlation_matrix,dtype=bool))
filtered_corr_matrix = correlation_matrix.where(mask)
np.fill_diagonal(filtered_corr_matrix.values, np.nan)

# Identify columns with correlation greater than 0.8
high_corr_pairs = []
for col in filtered_corr_matrix.columns:
    for idx in filtered_corr_matrix.index:
        value = filtered_corr_matrix.loc[idx, col]
        if not pd.isna(value) and abs(value) > 0.8:
            high_corr_pairs.append((idx, col,value))

# Print pairs of columns with high correlation
if high_corr_pairs:
    print("Columns with correlation > 0.8:")
    for pair in high_corr_pairs:
        print(f"{pair[0]} - {pair[1]} :{pair[2]:.2f}")
else:
    print("No columns with correlation > 0.8 found.")

# Define the columns to drop
columns_to_drop = ['Experience','MonthlyIncome','TotalAssets','BaseInterestRate','MonthlyLoanPayment']

X = X.drop(columns=columns_to_drop)

print(f"Dropped columns: {columns_to_drop}")
print(f"Updated DataFrame shape: {X.shape}")
print(f"Remaining columns: {X.columns.tolist()}")

print(y.head())

# Calculate the percentage of 1s and 0s in the 'y' variable

ones_percentage = (y == 1).sum() / len(y) * 100
zeros_percentage = (y == 0).sum() / len(y) * 100
print(f"1s in y: {(y==1).sum():}")
print(f"Percentage of 1s in y: {ones_percentage:.2f}%")
print(f"Percentage of 0s in y: {zeros_percentage:.2f}%")

# Split X to X_train and X_test and split y to Y_train and y_test

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

# Use SMOTE and upsample the dataset
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

print(f"Original dataset shape: {X_train.shape}, {y_train.shape}")
print(f"Resampled dataset shape: {X_resampled.shape}, {y_resampled.shape}")

ones_percentage_resampled = (y_resampled == 1).sum() / len(y_resampled) * 100
zeros_percentage_resampled = (y_resampled == 0).sum() / len(y_resampled) * 100

print(f"1s in y_resampled: {(y_resampled==1).sum():}")
print(f"Percentage of 1s in y_resampled: {ones_percentage_resampled:.2f}%")
print(f"Percentage of 0s in y_resampled: {zeros_percentage_resampled:.2f}%")
X_train=X_resampled
y_train=y_resampled

X_train.shape

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize models with predefined hyperparameters
models = {
    'logistic_regression': LogisticRegression(C=1.0, solver='liblinear', random_state=42),
    'random_forest': RandomForestClassifier(n_estimators=100, max_depth=None, min_samples_split=2, random_state=42),
    'xgboost': XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=6, random_state=42),
    'svm': SVC(C=1.0, kernel='rbf', gamma='scale', probability=True, random_state=42)
}

for model_name, model in models.items():
    # Train the model
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy for {model_name}: {accuracy}")

    print(f"Classification Report for {model_name}:")
    print(classification_report(y_test, y_pred))

    conf_matrix = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix for {model_name}:")
    print(conf_matrix)

    # Plot confusion matrix using seaborn
    plt.figure(figsize=(10, 7))
    sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
    plt.title(f"Confusion Matrix for {model_name}")
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.show()

    print("\n" + "-"*50 + "\n")

# Create a voting classifier
voting_clf = VotingClassifier(
    estimators=[
        ('lr', models['logistic_regression']),
        ('rf', models['random_forest']),
        ('svm', models['svm'])
    ],
    voting='soft'  # 'soft'
)

# Train the voting classifier
voting_clf.fit(X_train, y_train)

# Make predictions with the voting classifier
y_pred = voting_clf.predict(X_test)

# Evaluate the voting classifier
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy for voting classifier: {accuracy}")
print("Classification Report for voting classifier:")
print(classification_report(y_test, y_pred))

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix for voting classifier:")
print(conf_matrix)

# Plot confusion matrix for voting classifier using seaborn
plt.figure(figsize=(5,4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix for Voting Classifier")
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

# To the model who made using voting classifier, make the pkl file
import pickle

filename = 'voting_classifier_model.pkl'
pickle.dump(voting_clf, open(filename, 'wb'))

